### ISSUE TITLE
eventsource connection is dropped after 120ms in firefox

### ISSUE THREAD

**Issue by 2vek** [fgnass/instant-server#1]
On firefox 35 and firefox 37a2(developer edition), connection to `http://localhost:<port>/instant/events` is dropped at 120s ±100ms and doesn't even try to reconnect.

I have to manually press F5 to refresh the page, and see the changes, which defeats the point of using `instant`.

While on Chromium 40, connection persists even after a hour.

I tried this [event source demo](http://server-sent-events-demo.herokuapp.com/) on firefox, it kept running event after half hour, so it don't think it is firefox bug.

EDIT:
After some tinkering, it seems connection is only dropped if no changes are made, in past 120s, to ~~any files in the directory where `instant` is running.~~  current opened page or its linked files.

**Comment by fgnass** [comment]
If you reinstall instant-server (or perform an `npm update`) you'll get an updated `sendevent` version (1.0.3) that fixes this issue.

**Comment by 2vek** [comment]
Sorry, but it didn't work.

I reinstalled `instant-server`, and i got `sendevent@1.0.3` which is dependency of `instant`. Firefox still dropping connection after 120ms.

I am learning CSS from a book. I am reading text and then trying out things. And I have both Chromium and Firefox running side by side. After reading a page or two, If I change body background-color to red. Chromium recognizes it  but not Firefox.

If you check network tab of Firefox Developer tools, click on `events` request, a pane will open on right side. Click on timing tab on right pane. When connection is active, you will see nothing in "Receiving" label neither in response tab.

If nothing is changed in opened page, after 120ms(2min) connection will finish. In the "Receiving" label of timing tab you can see 120001ms or something. On other hand, In Chrome Dev tools, you can see new events connection in initiated after 2min. And on previous `event` request's timing tab, you can see "Content download" label with 2min. 

For now, as a workaround,  I have linked a blank `blank.css` and running this command on other terminal `watch -n115 touch blank.css` which update the timestamp of blank.css at every 115 seconds.

**Comment by fgnass** [comment]
Looks like a regression in Node 0.12 ... let my try something.

**Comment by fgnass** [comment]
Could you update it and test again? The update should install `sendevent@1.0.4` which resolves the issue for me.

**Comment by 2vek** [comment]
Thanks. It's working now.

Firefox has not dropped connection in past half hour and also Chromium is not reconnecting every two minutes.

:satisfied:
