### ISSUE TITLE
Unpublish / roll-back v1.1.0

### ISSUE THREAD

**Issue by sirreal** [fgnass/instant-server#4]
pr #3 looked pretty straightforward, didn't it?

With `instant-server@1.1.0` I'm only getting the first live-reload. Subsequent live-reload do not seem to have any impact.  Can you confirm this? Unpublish v1.1.0 from npm until this can be ironed out?

**Comment by fgnass** [comment]
I can't confirm this, but I noticed that instant-server wasn't using the most recent instant version. I updated the dependencies (including connect) and published a new version as 1.2.0. Maybe this already resolves your issue?

**Comment by sirreal** [comment]
Phew! 1.2.0 seems to be working correctly.

Using the same setup if I replace with 1.1.0 I continue to experience the 1st reload only bug. I'd still recommend unpublishing 1.1.0.
