### ISSUE TITLE
Error: listen EADDRINUSE

### ISSUE THREAD

**Issue by IbnSaeed** [fgnass/instant-server#5]
I am running a simple app, and i am using `instant-server localhost`

The first time i make any changes to the file, it reloads fine but 2nd time or more, it gives the following error. Though the browser is refreshed just  fine but it opens a new browser window with the update. 

```listening on port 3200 and waiting for changes events.js:85

``````
  throw er; // Unhandled 'error' event

        ^
Error: listen EADDRINUSE

at exports._errnoException (util.js:746:11)

at Server._listen2 (net.js:1146:14)

at listen (net.js:1172:10)

at Server.listen (net.js:1257:5)

at Function.app.listen (d:\node\site\node_modules\instant-server\node_modules\connect\lib\proto.js:188:24)

at Object.<anonymous> (d:\node\site\node_modules\instant-server\bin\instant:24:2)

at Module._compile (module.js:460:26)

at Object.Module._extensions..js (module.js:478:10)

at Module.load (module.js:355:32)

at Function.Module._load (module.js:310:12)```
``````

**Comment by IbnSaeed** [comment]
If i do not specify a PORT ( instant ), it does not give the above error

But it opens a new browser window with the updated site upon every single saved changed.
I am using chokidar for watching

here is the output

```
Watching "sources/style.css" ..
change:sources/style.css

listening on port 13382 and waiting for changes

change:sources/style.css

listening on port 13386 and waiting for changes

change:sources/style.css

listening on port 13390 and waiting for changes

change:sources/style.css

listening on port 13393 and waiting for changes

change:sources/style.css

listening on port 13401 and waiting for changes
Terminate batch job (Y/N)?
```

**Comment by fgnass** [comment]
Can you provide some more details on your setup? The actual code maybe? How (and why) do you use chokidar in this scenario?

**Comment by IbnSaeed** [comment]
I just want to use chokidar as a watcher. i can use any other if you have any suggestions which would work better with instant-server.

Here is my package.json

```
{
  "name": "grid",
  "version": "0.0.1",
  "description": "",
  "main": "index.js",
  "scripts": {
    "watch": "chokidar \"sources/style.css\" -c \"mingw32-make all\""
  },
  "repository": {
   },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "instant-server": "^1.2.0",
    "postcss": "^4.1.5",
    "postcss-cli": "^1.2.1"
  }
}
```

The postcss modules are used in the Makefile

Here is my the main part of the  makefile

```
assets/css/style.css: sources/style.css
    @mkdir -p $(@D)
    @set -e ; \
    $(BIN)/postcss -u somemodule -o $@ $^& $(BIN)/instant
```

**Comment by IbnSaeed** [comment]
I only tried chokidar, i can try others. Do you think chokidar is causing this issue ?

**Comment by fgnass** [comment]
No, I just wanted get the whole picture ;-) What your makefile does is to start a new server on each change. The previous instance keeps running and hence the port is already in use. You could probably move the invocation of `instant` to the line where you invoke chokidar like this:

```
"scripts": {
  "watch": "chokidar sources/style.css -c \"mingw32-make all\" && instant"
}
```

**Comment by IbnSaeed** [comment]
I tried your suggestion of && instant in package.json but it did not run as it did not open the browser.

So i tried the following and it worked, chokidar did not work

```
    "watch": "gaze \"mingw32-make all \" \"sources/*.css\" ",
    "reload": "instant",
    "start": "parallelshell \"npm run watch -s\" \"npm run reload -s\" "
```

Here is the result

```
$ npm run start                                                    

> parallelshell "npm run watch -s" "npm run reload -s"             

> gaze "mingw32-make all " "sources/*.css"                         

> instant                                                          

Watching 1 files/directories, pattern:  [ 'sources/*.css' ]        
listening on port 14800 and waiting for changes         

> mingw32-make all                                                 
Finished in 25 ms                                                  
Compiling CSS files to assets/css/style.css                        

> mingw32-make all                                                 
Finished in 33 ms                                                  
Compiling CSS files to assets/css/style.css                        

> mingw32-make all                                                 
Finished in 16 ms                                                  
Compiling CSS files to assets/css/style.css                        

> mingw32-make all                                                 
Finished in 20 ms                                                  
Compiling CSS files to assets/css/style.css                        

```

The refresh of the browser is not instant, it takes around 1 second, even though the compilation is taking 20 ms

I tried the following 

```
    "watch": "gaze \"mingw32-make all \" \"sources/*.css\" ",
    "reload": "instant",
    "start": "multiexec \"npm run watch -s\" \"npm run reload -s\" "
```

Refresh is around second mark, not miliseconds.
